spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
      static-path-pattern: /static/**
  freemarker:
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    cache: true
    expose-spring-macro-helpers: false
    request-context-attribute: request
    settings:
      classic_compatible: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.52.76:3306/sparchetype?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: admin
    password: 123456
    druid:
      initial-size: 8
      min-idle: 5
      max-active: 10
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filters: stat,config

logging:
  level:
    root: info
    com.songpeng: info